<?php
// $Id$

/**
 * @file
 * Install and uninstall hooks for Revisioning module
 */

/**
 * Implementation of hook_install().
 */
function revisioning_install() {
}

/**
 * Implementation of hook_uninstall().
 */
function revisioning_uninstall() {
  variable_del('revisioning_block_num_pending');
  variable_del('revisioning_block_order');
//@todo variable_del() content type dependent vars's
}
